### ISSUE TITLE
Return latest message from room

### ISSUE THREAD

**Issue by markzakharyan** [flyerhq/flutter_firebase_chat_core#15]
Hi everyone!

I want to be able to show the latest message (constantly updating, probably with StreamBuilder) on the Groups page.

Is there a way to return just the latest message from a room?

Thanks,
Mark

**Comment by demchenkoalex** [comment]
Hi @markzakharyan!

We can add `lastMessages` array to the room type for convenience (we planned to do so anyway for our own backend version) but to make it work with Firebase you will need to write a cloud function which will update that field when new messages come in. Will that work?

**Comment by demchenkoalex** [comment]
maybe, I'm not a cloud function expert and this is more "backend" related part. What we did provide in the example is more like an entry point on what can/should be done via cloud functions and then sky is the limit. We for sure can't provide them out of the box, because they are not related to Flutter in any way. Also, all cloud functions are now requiring paid plan and of course usage will be different for different people, another reason why we can't give you everything. What we can do is receive a tested solution from somebody in the community and add it to the docs, as an example implementation.

Regarding the "seen" status - there is a support for that in types and UI (if UI is used), but again somebody who knows backend and/or cloud functions can help out with the possible implementation and we can add whatever is needed (like a timestamp sent when user opens the chat or anything) to the core package.

**Comment by markzakharyan** [comment]
I made a PR containing firebase functions code adding `latestMessage` to firestore.

Here's code that works really well that retrieves the latest message:

```dart
Widget latestMessageFormat(String text) {
  return Text(text,
      style: TextStyle(color: Colors.grey, fontSize: 15, height: 1.1),
      maxLines: 2,
      overflow: TextOverflow.ellipsis);
}


var latestMessageDisplayText;
Widget _latestMessage(types.Room room) {
  return StreamBuilder<DocumentSnapshot>(
      stream: FirebaseFirestore.instance
          .collection('rooms')
          .doc('${room.id}')
          .snapshots(),
      builder:
          (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {
        if (snapshot.hasError) {
          return Text('Something went wrong collecting the latest message');
        }

        if (snapshot.connectionState == ConnectionState.waiting) {
          return latestMessageFormat(latestMessageDisplayText == null
              ? 'Loading...'
              : latestMessageDisplayText);
        }

        Map<String, dynamic> dataMap = snapshot.data!.data() as Map<String, dynamic>; //When in doubt, use a hashmap :D
        latestMessageDisplayText = dataMap.containsKey('lastMessage')
            ? dataMap['lastMessage']['text']
            : 'No messages yet';

        return latestMessageFormat(latestMessageDisplayText);
      });
}
```
The reason there's `latestMessageDisplayText` is to prevent flickering "Loading..." when a message is uploaded.

I'm pretty new to dart/flutter so I'm sure it could be improved but I'm actually pretty proud of it. It works well, so if anyone needs it, here it is to save the hassle.

**Comment by markzakharyan** [comment]
@demchenkoalex is there a way I can check if the user has seen the latest message? (or be at the bottom of the scroll) to check for their last read message

**Comment by demchenkoalex** [comment]
Not at the moment I think, but we are open for proposals

**Comment by demchenkoalex** [comment]
Everything related to the `seen` status we can continue here #9 and regarding the initial issue discussion is in #16. Closing this one.
