### ISSUE TITLE
room.lastMessages is Always null

### ISSUE THREAD

**Issue by mashegoindustries** [flyerhq/flutter_firebase_chat_core#25]
I am streaming rooms using code below
FirebaseChatCore.instance.rooms(orderByUpdatedAt: true)

However it looks like lastMessages is always null
room.lastMessages

I am 100 percent sure that I have last messages on the rooms collection (Which is updated by cloud function)

**Comment by markzakharyan** [comment]
i had the same issue, it could be that you didnt create a firestore index
![image](https://user-images.githubusercontent.com/56100600/126847225-7256a2b4-abab-4c0c-b34c-fbe9a15df67f.png)

**Comment by demchenkoalex** [comment]
Are you sure room at all is not empty? You need an index as described in the documentation comment for the `orderByUpdatedAt` or in the comment above. If you have it

> I am 100 percent sure that I have last messages on the rooms collection (Which is updated by cloud function)

So you can see `lastMessages` inside the console but not in the dart code?

**Comment by mashegoindustries** [comment]
I did create an index. Hence the rooms are showing nicely and the recent active room always appear at the top... Which is awesome.

I can see however lastMessages is always null NOT empty

**Comment by mashegoindustries** [comment]
[
<img width="1109" alt="Screenshot 2021-07-25 at 13 29 53" src="https://user-images.githubusercontent.com/16622091/126897544-4b9218c1-47e7-4662-b180-9f710188cf3f.png">
](url)

**Comment by demchenkoalex** [comment]
@mashegoindustries I understand, but is it null in the console? Why do you think this is a problem in the library and not in the cloud function which updates it?

**Comment by mashegoindustries** [comment]
<img width="978" alt="Screenshot 2021-07-25 at 17 04 06" src="https://user-images.githubusercontent.com/16622091/126903820-6f782145-7776-462c-8521-960937a6a9ab.png">

**Comment by mashegoindustries** [comment]
From console, it looks like Cloud functions has successfully updated last message

**Comment by demchenkoalex** [comment]
Are you saying you don't see `lastMessages` at all? Update to the latest version

**Comment by mashegoindustries** [comment]
@demchenkoalex I started from scratch, followed the instructions , created firestore index. Using latest version of the plugins.
However I am still not getting any last messages. Isn't the attached screenshot not the issue? lastMessages is never set 

<img width="1792" alt="Screenshot 2021-08-19 at 03 08 36" src="https://user-images.githubusercontent.com/16622091/129992013-0753d900-1c00-44b3-8bd9-928cc8591756.png">

**Comment by demchenkoalex** [comment]
LOL. How embarrassing :D sorry about that. You could have also done a PR with that so it would be released sooner. Will do now anyway.

**Comment by eopeter** [comment]
I need this fix too. Running into error 
`flutter type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type...`.

**Comment by eopeter** [comment]
I tried the highlighted lines in the screenshot above with 

`final lastMessages =  doc.data()?['lastMessages'] as List<dynamic>?;`

and then while creating the room, I did

`lastMessages: lastMessages != null ? lastMessages.map((e) => types.Message.fromJson(e)).toList() : <types.Message>[],`

But issue is the lastMessage only has authorId and the toJson is failing because author property is null and it expected a types.User map

**Comment by eopeter** [comment]
resolved author by setting it in cloud function for lastMessages but now it createdAt on lasts message is also failing because it expects an int and the value is DateTime. We may need to write a parser if one does not already exists.

![image](https://user-images.githubusercontent.com/2012979/130341912-68d40d03-7777-4df7-9ec4-04b8471045d5.png)

**Comment by demchenkoalex** [comment]
That's correct. My thought is to create a json from the document data, replace fields like DateTime etc to match the underlying data, and the pass it to the `fromJson` function, after I'll replace that with some package for JSON serialisation, because library became too big to manually parse things + this `dynamic` issue is driving me mad, hopefully some packages work better with whatever values are passed inside, when we know they are correct.

**Comment by demchenkoalex** [comment]
Fixed in [v1.3.0](https://github.com/flyerhq/flutter_firebase_chat_core/releases/tag/v1.3.0).
