### ISSUE TITLE
Support security rules determined by my own server

### ISSUE THREAD

**Issue by yoniker** [flyerhq/flutter_firebase_chat_core#40]
Hello 👋 

This real-world scenario is related to issue #6, but it's not quite the same question.
In most real-world applications, you want to limit a specific user to be able to create chat with a subset of users.

Let's take Tinder clone as an example.
The users interact with Tinder's server, which determines in turn which users are matched (both swiped right on each other's profiles). 
Only a pair of users who are already matched can chat with each other.
Tinder's server determines which users are matched or not.

I'm very unclear as to how I would Implement security rules which depend on my own server (for example, go to my server and get the current "matched with current user" users list).

In the documentation, there's the title "Firebase Chat with custom backend" which seems relevant, but to me, if this question was answered in the documentation, it's not straightforward. Also it says "This wasn't verified on production...", is this a concern?

**Comment by demchenkoalex** [comment]
Hi @yoniker documentation regarding custom server was only relevant to someone who don't use Firebase Authentication (e.g. has own server) and there is an example how to authenticate the user using own JWT token. Everything else should be handled on the Firebase's side, including security rules.

In your case you better have complete server solution, omitting this library completely, it would be extremely hard to make this work with different servers and use-cases.

**Comment by yoniker** [comment]
OK,just making sure that I understand you correctly (this will literally affect how I spend the next few weeks): Since my entire server's logic (it's an AI-based dating app so it's quite complicated) is implemented in flask/python(and pytorch,celery,docker etc), in general I shouldn't be using Firebase to implement chat because it will actually be more complicated than implementing the backend part of the chat on my own, do I understand you correctly?

If that's what you're saying, since unlike you I'm both a Firebase and chat newb (and since other people might be in my situation it is better to have this publicly for the benefit of others):

1. Since I'm going to implement my own chat backend, what would be a good starting point/tutorial, preferably something in python? I'm asking because I did look, and couldn't find a proper solution/explanation. Surely it involves more than saving the chat messages onto a DB...

2. For notifications, can I use firebase (FCM) when there's a match in that case, or will it be a huge headache as well and there's an easier solution for notifications? (the frontend of my app is Flutter).

**Comment by demchenkoalex** [comment]
If I were you, having that the backend is quite sophisticated already, and where chat is the code feature of the app, I wouldn't rely on this package, since I did not design it to perform in large applications and for sure I didn't plan to make it work with a custom backend, aside from the authentication. You can still use `flutter_chat_ui` though, since it was designed to be backend-agnostic, that means it can be used with your server side code.

We are actually working on our backend-as-a-service solution which will work with custom backends, but it won't be available soon, so can't suggest using it, but I believe you will be doing most of the work we did/will be doing too.

Unfortunately, I am a strictly mobile developer, coming from the iOS background, and backend/databases/python etc are dark magic for me, maybe @cristaloleg will be able to give you a hint or two.
