### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value on FirebaseChatCore.instance.createRoom(otherUser)

### ISSUE THREAD

**Issue by BillieVijo** [flyerhq/flutter_firebase_chat_core#43]
Hello 👋 

Having troubles with the method FirebaseChatCore.instance.createRoom(otherUser)

it says [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value

![image](https://user-images.githubusercontent.com/21168566/140163224-3e312504-8717-404f-a0a2-b34468cdce83.png)

my output shows some data with some null.

what am i doing wrong?

**Comment by demchenkoalex** [comment]
Hey @BillieVijo so basically some required field is missing in your data, there might be tons of cases why this has happened, so it would be easier if you'll debug it yourself, because to check on my side I will need your Firebase console, your project and time. 

If you use custom collection names instead of default ones `rooms`, `users` double check those are set before you use the library.

For every other case you can verify your data in the Firebase console to see if it matches the latest types https://github.com/flyerhq/flutter_chat_types

Also, as an idea, maybe debugger can help, if you set the breakpoints and go step by step you can find an exact line that crashes and you will know for sure which data is missing. Never used it though, so can't tell if this is possible.

**Comment by BillieVijo** [comment]
What am i missing on creating user. because when i check on firebase i see two fields with null(metadata and lastSeen)

```
await FirebaseChatCore.instance.createUserInFirestore(
        types.User(
          firstName: username,
          id: userId!, // UID from Firebase Authentication
          imageUrl: 'https://i.pravatar.cc/300',
          lastName: lastname,
          role: types.Role.user,
        ),
      );
```

**Comment by demchenkoalex** [comment]
@BillieVijo user looks good. The only required property for the user is `id`.

**Comment by BillieVijo** [comment]
@demchenkoalex  then why on creating room i still get the exception of Null check operator used on a null value?
i deleted all user to start again but didnt solve

**Comment by demchenkoalex** [comment]
@BillieVijo please read my first message, I can't possibly know this. Did you try to debug using breakpoints?
