### ISSUE TITLE
Isuue with messages stram

### ISSUE THREAD

**Issue by itaishalom** [flyerhq/flutter_firebase_chat_core#45]
Hi! I need a clarification.
`  Stream<List<types.Message>> messages(types.Room room) {`

It always returns all the messages from the room, which means that parsing all over the messages occurs on each new message, right? Don't you think it's time consuming?
Should the stream return only the updated document?
What do you think?

**Comment by demchenkoalex** [comment]
Yeah, this was done to fetch all messages, I though Firebase libs were smart enough to do the optimisations later. We will need to split between the load and update otherwise?

**Comment by itaishalom** [comment]
In my implementation, I first of all get all the messages currently on firestore and then listens to the updates:
[Check this stackoverflow question I have asked](https://stackoverflow.com/questions/69740756/firebase-firestore-getting-documents-again-on-query-stream)

**Comment by demchenkoalex** [comment]
Yeah, but this is like for the last added element. What about history or updates?

**Comment by itaishalom** [comment]
Well, on my implementation I first off all get all the messages and then the stream listens to updates, use "updatedAt" instead of createdAt to get updated messages. For deleted - I don't have a solution

**Comment by demchenkoalex** [comment]
Yeah, forgot about deleted ones.. So basically this was done as a proof of concept of the chat and planned as something that will work (and I need all updates so it works). Never planned further optimisations, because making and describing to different people and different use cases how it works - it does not make sense. Every case will be unique and there will never be a perfect library. So I think it should at least work as intended - as an early stage proof of concept, where you can show a working chat to your client and save some money on an initial implementation and then do a complete solution when client has more money to spend :)

**Comment by itaishalom** [comment]
Friend you did an excellent job!
If you were in Israel, we would hire you, definitely.
