### ISSUE TITLE
how to add more characteristic to users

### ISSUE THREAD

**Issue by Huynh-Anh** [flyerhq/flutter_firebase_chat_core#57]
<!--
Hello 👋 

Hey, so I try to change user.dart and add another field to the user type, but it doesn't seem to be possible ?
I simply added a string for the gender.
Can someone guide me ?

**Comment by demchenkoalex** [comment]
User has a metadata map, you can store whatever data you want there :)

**Comment by an99990** [comment]
could you make an example on how i would add data to the metadata ?
thank you

**Comment by demchenkoalex** [comment]
depends from where you want to add it? when creating a user? `createUserInFirestore` accepts a `User` type which has metadata field

**Comment by orangeRobot990** [comment]
after creating, so using the update method.
Can metadata take a list ?

**Comment by demchenkoalex** [comment]
metadata is a map - key value storage. It can store anything.

I noticed there is no `updateUser` in the lib, but you can done it yourself, similarly to this https://github.com/flyerhq/flutter_firebase_chat_core/blob/9432c388c702342e771670a0324410b3f1e1db0f/lib/src/firebase_chat_core.dart#L361 (you pasted a correct snipped, just instead of metadata: ? you need to pass full user object.

**Comment by orangeRobot990** [comment]
thank you it worked. I created a map and gave it to metadata.

**Comment by Huynh-Anh** [comment]
thank you it worked for me too
