### ISSUE TITLE
All users channel / group chat

### ISSUE THREAD

**Issue by gradycsjohnson** [flyerhq/flutter_firebase_chat_core#59]
First off, thanks for creating this great library! I was ecstatic to find a chat package that was actively maintained.

## Is your feature request related to a problem?
I have a multi-tenant app and I want to create a chat room (like a slack channel) for all the users of a given tenant.

Currently there doesn't seem to be a way to create a channel for all users. There's also no way to set the room ID.

I see there is a RoomType.channel, but it doesn't seem to be used anywhere.

There also seems to be no way to get messages without first getting the room. This seems unnecessary since messages should be reachable via the path {roomId}/messages

## What solution would you suggest?
I'd like to have a way to set the room ID, and a way to retrieve messages by room ID alone, instead of having to first get the room object. 

I'd also like to see Room.users as an optional parameter, with the default value being all users in the users collection. That is, all users should be able to see the room and interact with it, so long as the userIds list is empty

## Is there any additional solution to that?
I've fiddled around with dynamically adding users to the group room but haven't really had any luck. I'm open to suggestions though!

**Code snippets 📝**
I'm using Riverpod, so I'm building my ChatPage as a ConsumerStatefulWidget. The upshot being that certain methods must be called in the build method (like how I get my organization ID).

```dart
  @override
  Widget build(BuildContext context) {
    FirebaseChatCore firebaseChatCore = FirebaseChatCore.instance;
    String organizationId = organizationIdProvider(ref);
    FirebaseChatCoreConfig firebaseChatCoreConfig = FirebaseChatCoreConfig(
        Firebase.apps.first.name,
        'organizations/$organizationId/rooms',
        'organizations/$organizationId/users');
    firebaseChatCore.setConfig(firebaseChatCoreConfig);
    }
```

## Related issues/PRs
Not that I can see.

Thanks for your time and keep up the great work!

**Comment by demchenkoalex** [comment]
Hey @gradycsjohnson thanks for the detailed explanation. Chat UI itself (not a Firebase counterpart, those are unrelated) supports channel mode, that's why you see it in types. This one is pretty behind what Chat UI can do, because developing a UI is one thing, and developing a backend counterpart for every case out there - almost impossible. Like in your case, you have something specific, and others have something different. Since I am mostly alone right now (also I maintain React Native implementation) and I work full-time - I can't physically do anything about it. My best advice would be for you to fork this and re-do for your needs, or create something from scratch, you can use the code as a reference, you can also use types package, since it should contain everything you need (feel free to ask there to add anything you think is missing) and it will work with Chat UI. This way you will be able to achieve something, otherwise waiting for me to do it, well, I wouldn't count on that tbh.

**Comment by gradycsjohnson** [comment]
Hey Alex! Thanks for getting back to me so quickly! I'll see what I can do :)

**Comment by ernestkamara** [comment]
@gradycsjohnson Were you able to address your issue above? I have the same problem and would like to know how you proceed.
