### ISSUE TITLE
Use cases:  one to one, one to many

### ISSUE THREAD

**Issue by giorgio79** [flyerhq/flutter_firebase_chat_core#6]
Hello,

Fantastic docs so far!

Could you perhaps add some examples for one to one chats, or one to many (including firestore security rules etc)

Eg in case one to one, when someone is doing a tinder clone, there is no need for list of rooms probably.

**Comment by demchenkoalex** [comment]
Hi @giorgio79 thank you very much! 🙂

Yeah, for the Tinder clone there is no need for the list of rooms, however I tried to make everything optional, so you just do not use it if not needed. Let's imagine there is a button which says "Tap to start a chat" so having UIDs for both users you can create a room for them and you don't need to show it anywhere, but the room itself is needed to store messages somewhere :) If they exit the chat and try to open it again, there will be a check if a room for those users already exists so it would not be created twice and message history will be saved.

Regarding security rules I think they are not changing for this case, or there are subtle changes, I tried to left comments for every line in the docs so it should be straightforward to adjust.

Regarding one to many you mean group chat or like a channel where you post and others read? This is something new indeed and wasn't taken into consideration yet. We can think it over some time later since group chat is not completely working with chat UI at the moment and we are focused on that :)

Let me know if I didn't fully answered your question

**Comment by giorgio79** [comment]
Much appreciated Alex. This was exactly my question. I am interested in the Tinder clone (one to one) setup, so will take this baby for a spin.

**Comment by demchenkoalex** [comment]
Let us know how it'll go! :)
