### ISSUE TITLE
createUser doesn't return a populated room after creation

### ISSUE THREAD

**Issue by rootd** [flyerhq/flutter_firebase_chat_core#62]
# General

## What bug do you experience? 🐞
When creating a new room (with no entry in the Firebase database yet) using createRoom(), the room which gets returned the very first time doesn't any additional data besides the room ID. A second createRoom() call right afterwards is needed to receive a room which actually contains all the necessary data.

## How can it be reproduced? 🤔
Step 1. Delete the room with the other user from the firebase database
Step 2. Create a new room with the other user using createRoom()
Step 3. Overserve the returned room

## What behavior is expected? 💡
I expect createRoom to return a room with all values populated

# Extras

## Screenshots or videos 📸
Returned room after creating a new room with createRoom():
![createRoom1](https://user-images.githubusercontent.com/1213925/153201397-43eb1d93-8070-4660-af72-9549d3bcd3f9.png)

Returned room after calling createRoom() on a user with an already existing room:
![createRoom2](https://user-images.githubusercontent.com/1213925/153201412-e2d45a2e-2f75-4747-b301-758ddf649185.png)

My current workaround is to call createUser() twice. First time to actually create the room and then the second time to receive a proper room.

```dart
    await FirebaseChatCore.instance.createRoom(user);
    final types.Room room = await FirebaseChatCore.instance.createRoom(user);

    // ..open chat Widget
    Navigator.of(context).push(SwipeablePageRoute(
        builder: (BuildContext context) => ChatWithUser(room: room)));
```

<br />

# Environment info

flutter_firebase_chat_core: ^1.5.0

`flutter doctor -v` output 👇

```
flutter doctor -v
[✓] Flutter (Channel master, 2.10.0-1.0.pre.407, on Fedora Linux 35 (Workstation
    Edition) 5.16.5-200.fc35.x86_64, locale de_DE.UTF-8)
    • Flutter version 2.10.0-1.0.pre.407 at /home/alex/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a7e1c4fd34 (vor 6 Tagen), 2022-02-03 13:45:18 -0500
    • Engine revision e5433ffef9
    • Dart version 2.17.0 (build 2.17.0-79.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/<user>/Android/Sdk
    • Platform android-31, build-tools 32.1.0-rc1
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.14+9)
    • All Android licenses accepted.
```

<br />
<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
Hey, sorry for the long time no answer. I see what is the problem here. I return the following from the `createRoom` -

```dart
return types.Room(
  id: room.id,
  metadata: metadata,
  type: types.RoomType.direct,
  users: users,
);
```

and this is exactly what you see in the created room you log. Now when you create a direct room - `imageUrl` and `name` **must** be `null`, cause later library sets avatars and names of corresponding users, e.g. we talk in that room, you will see my avatar and my name, and I will see your avatar and your name, that is only possible if Firebase returns `null` in those fields and rest is done on the frontend. With the second call you break this - now in our dialog I will see myself and you will see me, but I talk to you, not myself :) `createdAt` and `updatedAt` are nulls because I use `FieldValue.serverTimestamp()` and I can't know it's value unless I will do fetch after create, but this is not needed in most cases. If you want to have those values, you need to fetch this room after creation, not create it again.

Hope that is clear. Thank you.
