### ISSUE TITLE
Multiple rooms for a pair of users

### ISSUE THREAD

**Issue by mrcnee93** [flyerhq/flutter_firebase_chat_core#87]
Hi,
i wandering if it's possible to create more then just one room for two users.
i'm already using metadata to keep track of the "topic" the two users are discussing in the said room, i'd really like to create a new room whenever i call createRoom passing differents metadata

**Comment by demchenkoalex** [comment]
Hi @mrcnee93 I think this will be impossible due to how dialogues work, I can't create different room to speak with the same person in any chat application I know. However, you could switch to group rooms? You can set your topic as a group room name, and you can have as many group rooms with same 2 people as you want.

**Comment by mrcnee93** [comment]
i didn't thought about this, i'll give it a try on monday, thanks!

**Comment by demchenkoalex** [comment]
Closing for now, feel free to add comments if needed :)
