### ISSUE TITLE
Implement Firebase Realtime Database backend 

### ISSUE THREAD

**Issue by giorgio79** [flyerhq/flutter_firebase_chat_core#90]
Would be nice to have an alternative backend to Firestore. Found this sample app for Firebase Realtime Database, perhaps we could use it here https://firebase.google.com/codelabs/firebase-android and the code at https://github.com/firebase/codelab-friendlychat-android

**Comment by znromonk** [comment]
I have a working code using the realtime database but it is nowhere near elegant for a public release or a PR. I am not sure how to go about formatting the code for a PR because there would need to be a provision to select between firestore and realtime db. If you need, I can share what I have here but not sure if it is allowed since it is a departure from this specific plugin.

**Comment by demchenkoalex** [comment]
Can be a separate lib tbh have no issues with that. Definitely will not want to support another huge backend SDK myself haha. I know you can have Firestore, RealtimeDB, Supabase, Appwrite, and probably tons of other stuff, but hey, you can only do so much.

**Comment by znromonk** [comment]
I have created a new repo with the code. Feel free to fork/publish. There is minimal documentation since a lot of if is common with this plugin. There is an example included which is minimally modified to account for the new plugin.

https://github.com/znromonk/flutter_realtimedb_chat_core

**Comment by demchenkoalex** [comment]
All good @znromonk! Thanks :)

**Comment by giorgio79** [comment]
Fantastic, thx @znromonk  Will try to play with it in the coming weeks :)

**Comment by giorgio79** [comment]
PS Meanwhile, I also found a full firebase codelab on creating chat with realatime db https://firebase.google.com/codelabs/firebase-android#0
